
  CREATE OR REPLACE PROCEDURE "DMPROD"."PROC_LOAD_VOUCHERS_JO" AS
  v_ORDER_DATE      DATE;
  v_TRAY_FROM       VARCHAR(100);
  v_TRAY_TO         VARCHAR(100);
  v_ORDER_NO        VARCHAR(100);
  v_VOUCHER_NUMBER  VARCHAR(100);
  v_QUANTITY       NUMBER;
  v_TRAY_FROM_N       NUMBER;
  v_TRX_TYPE         VARCHAR(100);
  v_VOUCHER_TYPE        VARCHAR(100);
  v_FACE_VALUE      NUMBER;

  

BEGIN
DECLARE
CURSOR C1 IS select TRX_TYPE,ORDER_NO,ORDER_DATE,VOUCHER_TYPE,FACE_VALUE,TRAY_FROM,TRAY_TO,TRAY_QUANTITY  from BH_1;

BEGIN

OPEN C1;

LOOP
FETCH C1 INTO v_TRX_TYPE,v_ORDER_NO,v_ORDER_DATE,v_VOUCHER_TYPE,v_FACE_VALUE,v_TRAY_FROM, v_TRAY_TO, v_QUANTITY  ; 
EXIT WHEN C1%NOTFOUND;

v_TRAY_FROM_N := TO_NUMBER(v_TRAY_FROM);

FOR TRAY IN 0 .. v_QUANTITY -  1
LOOP
v_VOUCHER_NUMBER :=  '0' || TO_CHAR(v_TRAY_FROM_N + TRAY);
INSERT INTO BH_2(ORDER_NO,ORDER_DATE,TRAY_FROM,TRAY_TO,TRAY_SEQUANCE,TRX_TYPE,VOUCHER_TYPE,FACE_VALUE)
VALUES ( v_ORDER_NO,v_ORDER_DATE, v_TRAY_FROM, v_TRAY_TO,v_VOUCHER_NUMBER,v_TRX_TYPE,v_VOUCHER_TYPE,v_FACE_VALUE);


END LOOP;
Commit;
END LOOP;

CLOSE C1;

EXCEPTION
WHEN NO_DATA_FOUND THEN
rollback;
WHEN OTHERS THEN
rollback;
RAISE;
END;
END ;
 
